CHANGELOG.md
fluentd/http/Chart.yaml
fluentd/http/values.yaml

Currently the subsystem name is configured to be `kubernetes.container_name` and doesnt allow any changes. 
Changing the subsystem kubernetes field to `come from an env`, allowing it to be override.

Fix/fluentd: subsystem is hardcoded instead of coming from an environment variable 

---

cxtool/cx-integrations

In case we are running the script within its dir, and not via sym link, the readlink command will fail.
Therefore, in case the readlink command returns exit code 1, Im setting the current path to . instead of the link path

FIX: add exit status check for the readlink command

---

fluent-bit/image/Dockerfile

Upgrade fluentbit image - in version 1.9.2 there is a bug on `nest filter` that doesnt allow using multiple wildcards as we use in our charts. 
Fixed in 1.9.3

Upgrade Fluentbit image due to a bug in previous version

---

CHANGELOG.md

Upgrading Fluentbit from 1.9.2 to 1.9.3 due to a bug fix. Override the current 0.0.2 release.

Update fluentbit changelog - upgrading fluentbit to 1.9.3

---

README.md
opel-agent/CHANGELOG.md
opel-agent/Chart.yaml
opel-agent/README.md
opel-agent/exmaples/override.yaml
opel-agent/values.yaml

* **Changed the `pipeline order`** - now metrics and logs are null [disabled] in the pipeline `after the traces section`. By having them before the tracing, the are enabled automatically, so the order affects it.  
* Update `main readme` to include the new otel chart in addition to the fluent charts and add some small fixes
* Update `otel-agent readme`, to get some info from the main readme
* Update the agent `installation command` - after some checks, its impossible to use `--set` to override only specific envs, it requires to set the whole envs in the installation command which is very complicated. 
Therefore, it requires to create an `override.yaml` file which includes all of the envs in order to change an env.
* Update the otel-agent secret to be the same secret as the fluent charts …

FIX: disabling metrics and logs pipeline, update READMEs

---

opel-agent/CHANGELOG.md
opel-agent/Chart.yaml
opel-agent/values.yaml

Chart updates : 
* Default resources decreased - cpu is now 256m instead of 1core, and memory is now 512Mi instead of 2Gi [we set the limits to ourselves so its ok] 
* they added support for running the collector as a statefulset
App version updates:
* They deprecated some configs that we didnt use , and added some new features, not supposed to affect us and to break something

Upgrade opentelemetry collector app and chart version

---

opel-agent/CHANGELOG.md
opel-agent/Chart.yaml
opel-agent/values.yaml

Add binary protocol to Jaeger to support nodejs traces , see : https://www.jaegertracing.io/docs/1.23/client-features/

Add binary protocol to jaeger agent

---

opel-agent/CHANGELOG.md
opel-agent/Chart.yaml
opel-agent/values.yaml

The default endpoint must be set , therefor setting the endpoint for the binary protocol

Set default endpoint to jaeger binary protocol

---

otel-agent/CHANGELOG.md
otel-agent/Chart.yaml

* Upgraded chart version - there were no changes in the chart itself, but it upgrades the otel collector version from 64 to 66. 
* Updated changelog both retro and for current version
* version v0.66.0 - it has a few small updates like: Add AWS CloudWatch Receiver, add snmp receiver, small bug fixes

Upgrade chart and app version to v0.66.0

---

otel-agent/Chart.yaml

Until we enable our workflow to be triggered manually after it fails, by adding 'workflow_dispatch' to the workflow, 
we must push something to the otel-agent directory in order to trigger it to run again

Push in order to trigger the workflow

---

otel-agent/CHANGELOG.md
otel-agent/Chart.yaml
otel-agent/values.yaml

Without setting these to null, it disable them completely, so no hostmetrics are included except filesystem metrics

FIX: hostmetrics didnt include anything except filesystem metrics

---

otel-agent/CHANGELOG.md
otel-agent/Chart.yaml
otel-agent/values.yaml

By adding this filter, the agent will query pods running on the same node only.
`It reduces resource usage`. 
As you can see in the following img , the amount of hosts the agent is querying before using this filter was much higher, 
which affected the resources usage.

Set node_from_env_var filter for k8sattributes

---

otel-infrastructure-collector/CHANGELOG.md
otel-infrastructure-collector/Chart.yaml
otel-infrastructure-collector/values.yaml

* When using both the `otel-agent` and the `infrastructure-collector` we need to separate the **prometheus jobs** in order to be able to monitor both and have separate alerts on both collectors. 
* PodMonitor cant be enabled in deployment mode so changing to `ServiceMonitor`
* Added `CHANGELOG`

Update prometheus job_name and serviceMonitor

---

.github/workflows/prometheus-agent.yml
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/README.md
metrics/prometheus-agent/override.yaml
metrics/prometheus-agent/templates/_helpers.tpl
metrics/prometheus-agent/templates/clusterrole.yaml
metrics/prometheus-agent/templates/clusterrolebinding.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/templates/serviceaccount.yaml
metrics/prometheus-agent/values.yaml

Creating a new helm chart for Prometheus in agent mode. 
The goal here is to enable sending metrics to Coralogix, with focusing only on remote write, on scraping and sending, without having all of the extra components like rules, alerting, querying. 
* Requires to install the Prometheus operator
* Requires to have the privatekey secret
* Requires to create a new override file in order to override the Coralogix url 
* Add a Grafana dashboard for remote write

Create a helm chart for Prometheus Agent

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/override.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/values.yaml

The Prometheus agent needs a `disk` to keep the data when needed, 
and the storage configuration was not supported in the `template` until now.
So adding to the template , updating the override.yaml example file

FIX: Add missing storage template to Prometheus agent

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/override.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/values.yaml

In order to use externalLabels in remoteWrite, we need to be able to specify the external labels , which was not supoprted until now

Add externallabels support to the prometheus template

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/values.yaml

* Update `appVersion` in the Chart.yaml to Prometheus version and not the operator version
* Update `Prometheus template` to include image repo and tag
* Set specific Prometheus `image` so it won't take always the latest

Add Prometheus image values and update the template

---

CHANGELOG.md
logs/fluent-bit/k8s-helm/coralogix/Chart.yaml
logs/fluent-bit/k8s-helm/coralogix/values.yaml
logs/fluent-bit/k8s-manifest/fluentbit-cm.yaml
logs/fluent-bit/k8s-manifest/fluentbit-ds.yaml
logs/fluent-bit/k8s-manifest/fluentbit-svc-monitor.yaml
logs/fluent-bit/k8s-manifest/fluentbit-svc.yaml

I'm upgrading the fluent-bit version to 2.0.8 since we have new features like the new internal metrics plugin as described [here](https://docs.fluentbit.io/manual/pipeline/inputs/fluentbit-metrics) and also because this version has available features which can improve the performance on high volume environments such as the threaded mechanism allows input plugins to run in a separate thread which helps to desaturate the main pipeline and move certain loads to a different CPU core.
Because we want to enable the storage metrics by default, we also need to upgrade to the latest helm chart version which allows the configuration of `additionalEndpoints` on the ServiceMonitor and also the VPA manifest of non-enabled features.
Signed-off-by: Nicolas Takashi <nicolas.takashi@coralogix.com>

[FEAT] upgrading fluent-bit helm chart

---

CHANGELOG.md
logs/fluent-bit/k8s-helm/http/Chart.yaml
logs/fluent-bit/k8s-helm/http/values.yaml

I'm upgrading the fluent-bit version to 2.0.8 since we have new features like the new internal metrics plugin as described [here](https://docs.fluentbit.io/manual/pipeline/inputs/fluentbit-metrics) and also because this version has available features which can improve the performance on high volume environments such as the threaded mechanism allows input plugins to run in a separate thread which helps to desaturate the main pipeline and move certain loads to a different CPU core.
Because we want to enable the storage metrics by default, we also need to upgrade to the latest helm chart version which allows the configuration of `additionalEndpoints` on the ServiceMonitor and also the VPA manifest of non-enabled features.
Signed-off-by: Nicolas Takashi <nicolas.takashi@coralogix.com>

[FEAT] upgrading fluenbit http charts

---

otel-agent/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml

I'm upgrading OTEL helm chart version to be able to use the latest OTEL version and leverage k8sobjectreceiver

[UPDATE] otel helmchart version

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml

When using the default values which include `storageSpec: {}`,
it set the storage as {} inside the final yaml file, which is causing the following error:  
`PersistentVolumeClaim "prometheus-agent-0" is invalid: spec.resources[storage]: Required value` .
Therefore im changing it - if the storageSpec is not empty, is takes the values, otherwise, the storage field won't appear at all

FIX: update prometheus agent storage template to allow empty value

---

otel-infrastructure-collector/k8s-helm/CHANGELOG.md
otel-infrastructure-collector/k8s-helm/Chart.yaml

Upgrading the upstream helm chart to the latest version, so that we can leverage the upgrades on k8sobjects receiver and watch events instead of pull.

[CHORE] upgrading otel helm chart

---

otel-agent/k8s-helm/README.md

The port number used in the example code for the OTEL_EXPORTER_OTLP_ENDPOINT was incorrect and would cause an instrumented pod to be unable to send traces to OTEL.
I have updated the port number in the documentation and also made some minor clean-up changes to the markdown (not yaml !) in the readme.

Fix for OTEL Agent k8s Helm Chart docs

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/_helpers.tpl
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/templates/serviceMonitor.yaml
metrics/prometheus-agent/values.yaml

I'm changing the Prometheus agent to use default values in terms of shards and max samples sent and also adding a self-monitor feature as well as a snapshot on WAL to improve restarts.

[FEATURE] changing prometheus agent to use default configs

---

logs/CHANGELOG.md
logs/fluentd/k8s-helm/http/Chart.yaml
logs/fluentd/k8s-helm/http/README.md
logs/fluentd/k8s-helm/http/values.yaml

`PodSecurityPolicy` is deprecated in Kubernetes v1.21+, and unavailable in Kubernetes v1.25+, 
therefore - Im disabling the PodSecurityPolicy by default [in fluentbit its already disabled by default]. 
* Also moved the changelog to the logs directory because it was at the root path but its only related to fluentd fluentbit

Disable PodSecurityPolicy for Fluentd

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml

Since we're creating our own Prometheus CRD, because Prometheus Operator still doesn't have Prometheus Agent Available, we need to change the logs config from the CRD Properties to the container flags

[FIX] Prometheus Agent logs configuration

---

logs/fluent-bit/k8s-manifest/fluentbit-ds.yaml

The created configmap name is fluent-bit not fluent-bit-env

Corrected referenced configmap name

---

metrics/prometheus-agent/values.yaml

As part of my onboarding, I'm attempting a small change to the observability stack 😅.
This PR aims to update the image version of Prometheus Agent and [bring memory improvements with it](https://github.com/prometheus/prometheus/releases/tag/v2.43.0).
The memory improvements are mostly on how Labels are indexed. Since we're using Agents, the storage layers is not used that much, so I don't expect to see a huuuuuge improvement. The main reason for this PR is for me to experience how deployments work at Coralogix 😛

Update prometheus-agent version to `v2.43.0-stringlabels`

---

.github/pull_request_template.md
.gitignore

Part of #216.
This change adds a PR template to the repo to include simple requirements (describe changes and check that the submitted updated the Chart version and changelog).

*: Add PR template

---

.devcontainer/devcontainer.json

This PR configures [devcontainers](https://containers.dev/), so it can be used by Cloud Developer Environments(CDE) such as  [Codespaces](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers) and [DevPod](https://devpod.sh/docs/developing-in-workspaces/devcontainer-json).
The idea behind CDEs and devcontainer is to standardize our developer environments, making sure all tools needed for the development of telemetry shippers are available and with the correct versions.
For me at least, it would save a lot of time 😅 since I wouldn't need to download these tools every time I open a CDE. I haven't received my work laptop yet (still 2 weeks until it arrives) and I've been coding on CDEs for the past 3 …

Setup devcontainers for automated Developer Environments.

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml

Providing null values is not allowed for this object thus I provided default values as per the [official prometheus community repo](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml)
error received when trying to apply:
```
Prometheus.monitoring.coreos.com "prometheus-agent" is invalid: [spec.disableCompaction: Invalid value: "null": spec.disableCompaction in body must be of type boolean: "null", spec.retention: Invalid value: "null": spec.retention in body must be of type string: "null", spec.alerting: Invalid value: "null": spec.alerting in body must be of type object: "null", spec.ruleNamespaceSelector: Invalid value: "null": spec.ruleNamespaceSelector in body must be of type object: "null", …
```

fix default values for prometheus.monitoring.coreos.com/v1

---

metrics/prometheus/operator/Chart.yaml
metrics/prometheus/operator/README.md

Update dependency `prometheus-kube-stack` to use latest version due to previous versions using `autoscaler/v1beta` which is now deprecated since v1.23+
Fixed on this [PR](https://github.com/prometheus-community/helm-charts/pull/3413) (also by me :) )
Above PR will pull the latest image tag of kube-state-metrics which already uses `autoscaler/v1`

[prometheus-operator-coralogix] Update prometheus-kube-stack chart version

---

metrics/prometheus/operator/Chart.yaml
metrics/prometheus/operator/README.md
metrics/prometheus/operator/values.yaml

Upgrade kube-prometheus-stack version and remove previous hack made in 0.0.3
Fixes #
Fixes https://github.com/prometheus-community/helm-charts/pull/3400
Deployed in our cluster
* Ran helm template on local chart and verified the issue no longer happens
* Reviewed the following [PR](https://github.com/prometheus-community/helm-charts/pull/3400) fixes

upgrade kube-prometheus-stack to fix a bug in 45.30.0

---

otel-agent/k8s-helm-windows/CHANGELOG.md
otel-agent/k8s-helm-windows/Chart.yaml
otel-agent/k8s-helm-windows/README.md
otel-agent/k8s-helm-windows/values.yaml
otel-agent/otel-collector-windows-image/README.md

[SC-18267]
Use the "official" Coralogix image instead of the testing one.
N/A.

[k8s-helm-windows] Use image from Docker Hub 

---

otel-agent/CHANGELOG.md
otel-agent/ecs-ec2/config.yaml
otel-agent/ecs-ec2/logging.yaml

updated default otel config for ecs agent to support domain key for Coralogix Exporter

[CDS-337] updated default otel config for ecs agent to support domain key for Coralogix Exporter

---

.github/workflows/fluentd-standalone-image.yml
logs/CHANGELOG.md
logs/fluentd/k8s-helm/coralogix/values.yaml
logs/fluentd/k8s-helm/http/Chart.yaml
logs/fluentd/k8s-helm/http/values.yaml
logs/fluentd/k8s-manifest/fluentd-ds.yaml
logs/fluentd/standalone-image/README.md

v1.15.2 image
Updated fluentd deployments to use the previously updated multiarch image based on v1.15.2 of fluentd.
Threw in a deprecation notice for the standalone image as we no longer support the Coralogix fluentd plugin.
Deployed from local helm chart to EKS, ECS via cloudformation and locally.
Installed locally and looked for any install errors. Reviewed pod "logs" to ensure no errors. Reviewed Coralogix platform for ingest of new messages.

FEAT - Upgrade all fluentd deployments to use new

---

logs/CHANGELOG.md
logs/fluentd/k8s-helm/coralogix/values.yaml

Downgraded the 'coralogix' plugin based fluentd deployment to use the old version as it is no longer maintained and no QA testing was performed on the new version of fluentd
It wasn't, restoring to previously tested version.

BUG - revert fluentd coralogix version

---

otel-agent/k8s-helm/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml
otel-agent/k8s-helm/README.md
otel-agent/k8s-helm/values-crd.yaml

Part of ES-29.
This PR adds feature to generate the `otel-agent` as the OpenTelemetry Operator CRD. The feature is explained and documented in the README.
Manually tested on local cluster

Introduce CRD generation

---

otel-agent/k8s-helm/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml
otel-agent/k8s-helm/templates/NOTES.txt
otel-agent/k8s-helm/values-crd.yaml

Adds validation to our `otel-agent` chart to check if domain (or endpoint(s)) is set. This will prevent the user from accidentally installing the chart without providing domain, which results in collector crashing with error message about missing configuration. Stopping the chart installation will provide a better user experience.
Additionally, removes the default domain for the CRD chart, which was added accidentally.
Manually on local cluster.

[otel-agent] Add domain validation via `NOTES.txt`

---

otel-agent/ecs-ec2/CHANGELOG.md
otel-agent/ecs-ec2/ecsattributesprocessor/docker.go

This PR fixes an issue with the ecsattributes processor where it does not sync metadata until 60 seconds after the processor has been started.
Fixes #

[CDS-305] Fix initialisation delay for metadata on ecsattributes processor

---

otel-agent/ecs-ec2/CHANGELOG.md
otel-agent/ecs-ec2/ecsattributesprocessor/README.md
otel-agent/ecs-ec2/ecsattributesprocessor/ecsattributes.go
otel-agent/ecs-ec2/ecsattributesprocessor/ecsattributes_test.go
otel-agent/ecs-ec2/ecsattributesprocessor/factory.go
otel-agent/ecs-ec2/ecsattributesprocessor/metadata.go

This PR fixes:
- An issue with the `ecsattributes processor` adding empty labels when no metadata is detected.
Implements:
- Support for retrieving and adding custom docker labels to log attributes.
Fixes #

[CDS-305] stop ecsattributes processor adding empty attributes 

---

otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md

Part of [ES-55](https://coralogix.atlassian.net/browse/ES-55).
This PR fixes a typo in the chart name which caused the chart to not be uploaded. Also fixes incorrect instruction in the README.
Locally.
[ES-55]: https://coralogix.atlassian.net/browse/ES-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[otel-integration] Fix typo and instructions in the integration chart

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Part of [ES-55](https://coralogix.atlassian.net/browse/ES-55).
- Fixes wrong port configuration
- Adds `k8s.node.name` resource attribute to cluster collector
- Allows override for cloud provider resource detectors over the default system attributes
Locally
[ES-55]: https://coralogix.atlassian.net/browse/ES-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[otel-integration] Fix ports; improve resource attributes

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml

Bump fork to `0.67.0` to bring in latest preset changes.
Locally

[otel-integration] Bump dependency chart to 0.67.0

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Reflects some changes done in `monitoring-shipper`.
- Add some extra metrics regarding allocatable resource on cluster
- Remove unused integration version attribute to lower cardinality
Locally.

[otel-integration] Add allocatable metrics; drop unused version attribute

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

The transform processor for `kube-event` does not currently work as expected. This change fixes it's configuration to properly filter the log `body` and retaining only fields required for the K8s dashboard feature.
Locally
- [] This change does not affect any particular component (e.g. it's CI or docs change)

[otel-integration] Fix kube events transform

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes mainly moving extra Kubernetes to collector instead of agent by bumping the fork version. 
Also improves KSM instance filtering and adjusts the node label for node info metrics.
Locally on a multi-node setup.

[otel-integration] Bump fork version and fix node label

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

The K8s dash-boarding feature requires us to have a uniform integration name attribute. This change is in order to align our integration name attributes to be `coralogix-integration-helm`.
Locally

Align integration name attribute with internal requirements

---

otel-agent/k8s-helm/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml
otel-infrastructure-collector/CHANGELOG.md
otel-infrastructure-collector/k8s-helm/Chart.yaml
otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml

Upgrading the upstream chart to use the latest coralogix otel helm chart

[CHORE] upgrading upstream helm chart

---

otel-agent/k8s-helm/README.md
otel-infrastructure-collector/k8s-helm/README.md
otel-integration/k8s-helm/README.md

Clarifies the required minimal versions for Helm and Kubernetes. This is required for any chart using the `opentelemetry-collector` subchart.
N/A

Update README with prerequisites

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values-crd.yaml
otel-integration/k8s-helm/values.yaml

Resolves [ES-28](https://coralogix.atlassian.net/browse/ES-28) and [ES-30](https://coralogix.atlassian.net/browse/ES-29).
Adds CRD generation feature and MySQL preset to `otel-integration` chart. Also documents the new features in detail.
Locally.
[ES-28]: https://coralogix.atlassian.net/browse/ES-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ES-30]: https://coralogix.atlassian.net/browse/ES-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[otel-integration] Add CRD generation and MySQL preset features

---

.github/workflows/checks.yml
otel-agent/otel-collector-windows-image/Dockerfile

Bumps collector version to `0.81.0` (corresponds to current version on our other charts).

[otel-collector-windows-image] Bump collector to 0.81.0

---

otel-agent/k8s-helm-windows/CHANGELOG.md
otel-agent/k8s-helm-windows/Chart.yaml
otel-agent/k8s-helm-windows/templates/_config.tpl
otel-agent/k8s-helm-windows/values.yaml

Fixes [ES-66](https://coralogix.atlassian.net/browse/ES-66).
This removes the `memory_ballast` extension from the Windows chart. As our investigation has shown, on Windows platforms the extension does not work as a expected and using the memory ballast extension will actually cause the collector to use up all the memory marked as ballast, regardless of resource limits. To prevent this extensive resource usage, we are removing this extension on Windows platforms.
On EKS Windows node.
[ES-66]: https://coralogix.atlassian.net/browse/ES-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[otel-agent] Remove ballast extension for Windows chart

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

The `fullnameOverride` in the Values file has a redundant "-agent" at the end. When following the default installation pattern this yields pods that have names like `coralogix-opentelemetry-agent-agent-xxxxx`. 
Yes, I deployed the default configuration, as-is, and you will see it as the attache screenshot. After deleting everything and trying it again without the redundant "-agent" everything is name correctly. No functional difference between either scenario.

[FIX] Remove redundant `-agent` from `fullnameOverride` field of `values.yaml`

---

otel-agent/otel-collector-windows-image/Dockerfile

Build Windows Docker image with latest collector version we use in other charts.
N/A

Bump Windows image Dockerfile to 0.83.0

---

otel-agent/k8s-helm-windows/CHANGELOG.md
otel-agent/k8s-helm-windows/Chart.yaml
otel-agent/k8s-helm-windows/values.yaml

Bumps Windows collector version and uses version specified in Chart file.
Locally.

[otel-agent] Bump Windows collector image version

---

otel-agent/k8s-helm/README.md
otel-infrastructure-collector/k8s-helm/README.md
otel-integration/k8s-helm/README.md

Relates to https://coralogix.atlassian.net/browse/ES-71.
Some users are not familiar with how Helm behaves when arrays are being overridden by their custom values (see https://github.com/helm/helm/issues/3486). This PR informs our users of this behavior and instructs them to copy over any existing values in order to ensure agent / collector config works as expected.
N/A

Update READMEs with note on array merging

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-102.
Add support for running agent sub-chart on Windows node. This removes the need for user to use the deprecated `otel-agent` and can instead run everything with `otel-integration` chart.
On EKS test cluster.

[otel-integration] Add support for Windows node agent

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Removes unnecessary configuration from cloud provider resource detectors, since the specified attributes are already enabled by default.
N/A

Remove unneeded config from cloud provider resource detectors

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-137.
Locally on `kind`

Ensure correct attributes and order of processors for `k8s.deployment.name` workaround

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values.yaml

Fixes issue discovered https://coralogix-dev.slack.com/archives/C04HUCDGHTK/p1702378190750739
Use correct labels for target allocator deployment. Previously this was causing issues with incorrect pods being picked up by target allocator as collector pods. After this change everything works as expected.
Locally with `kind`.

[otel-integration] Fix target allocator labels, documenting replica parameter

---

otel-agent/ecs-ec2/CHANGELOG.md
otel-agent/ecs-ec2/config.yaml
otel-agent/ecs-ec2/logging.yaml

Update the default configs taken from the CF template

[ecs-ec2] Update default configs

---

otel-agent/README.md
otel-ecs-ec2/README.md
otel-eks-fargate/CHANGELOG.md
otel-eks-fargate/cx-eks-fargate-otel-self-monitoring.yaml
otel-eks-fargate/cx-eks-fargate-otel.yaml
otel-integration/CHANGELOG.md

Add nodeSelector to constrain otel deployment to fargate nodes when in a mixed ec2+fargate eks cluster.
Fixes  [CDS-854](https://coralogix.atlassian.net/browse/CDS-854).
OTEL pods deploy to Fargate nodes only in a mixed EC2+Fargate EKS cluster. 
[CDS-854]: https://coralogix.atlassian.net/browse/CDS-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[eks-fargate-otel] deploy to fargate node when in mixed ec2+fargate cluster

---

otel-integration/k8s-helm/README.md

The environment variable default value should contain a prefix of `http` or `https`.
Once using an internal k8s value, the most common usage would be a `http` prefix
Deployed the chart with and without the change;
- without the agent's failure to report data

Fix otel exporter otlp endpoint example value

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

- Bumps Windows agent image to latest (`0.91.0`)
- Disable trace pipeline in the collector, since it's unused
Locally

[otel-integration] Update Windows image and disable trace pipeline on collector

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-173
Adds parameter to specify span metrics histogram buckets and uses fewer buckets as default.
Bumps collector to `0.92.0`.
Locally on `kind`

[otel-integration] Add histogram buckets and bump collector to `0.92.0`

---

otel-integration/k8s-helm/README.md

Clarify better how users should install special integrations (CRD, Windows, GKE Autopilot).
N/A

Clarify docs on installing special integrations

---

.github/workflows/Sync-integration-definition.yaml

The sync action is not working when it is triggered from a fork branch because it has no access to the repo secrets.
I have changed the action to be triggered when there is a new commit in master so that it will always have access to the repo secrets, also added an option to run the action manually
Fixes #

Fix a bug in the sync action

---

.github/workflows/Sync-integration-definition.yaml

The sync action creates a PR in the integration-definitions repo using commit message as the name of the PR, in this PR i have changed it so that the name of the PR in integration-definitions repo will be the last PR that was merged into master
Fixes #

Update the pr name that get created by the sync action

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/values.yaml

Adding missing templates to Prometheus Agent
Helm template with new values

[CHORE] adding missing templates

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-203.
Fix warning that shows up when installing the chart - this is due to mismatch between the value types (null vs object). Simply removing the tracing pipeline from config here, since it's not needed (upstream chart will still add a dummy trace pipeline that exports to debug).
Locally with `kind`.

Fix trace pipeline warning during install

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-53
Adds limit to batch processors by default, to prevent customers having issues with the limit imposed by our endpoints (https://coralogix.com/docs/opentelemetry/#limits--quotas). Also documents this.
Locally.

Add batch size limit

---

otel-collector-windows-image/Dockerfile
otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-215 and https://coralogix.atlassian.net/browse/ES-189
- Bump collector to 0.96.0, including the Windows image
- Use upstream target allocator image, removing the need for us to have our custom fork 🥳 
Locally with `kind`

[otel-integration] Bump collector version to 0.96.0 and use upstream target allocator

---

logs/fluent-bit/ecs-fargate/README.md

Updated the IAM policy required to access the s3 bucket
Deployed the integration with the updated IAM permission.

[ecs-fargate] Fixed IAM permissions required by fluent-bit to access s3

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/tail-sampling-values.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-219
Fixes the problem with inability to override tail sampling processor configuration and the default values that are too low.
Locally with `kind`

[otel-integration] Fix tail sampling configuration

---

logs/fluent-bit/ecs-fargate/README.md
otel-ecs-fargate/README.md

FEAT - Document the use of AWS Secrets Manager for the API key
Added steps to use Secrets Manager for the private key instead of exposing it in the task definition.
Fixes CDS-1146
Tested in AWS ECS with OTEL instrumented test applications

FEAT - Document the use of AWS Secrets Manager

---

logs/CHANGELOG.md
logs/fluent-bit/k8s-helm/http/Chart.yaml
logs/fluent-bit/k8s-helm/http/values.yaml
logs/fluent-bit/k8s-manifest/fluentbit-ds.yaml

Updated the fluentbit helm and kubernetes manifests to use the new 3.0.2 image.
Deployed into EKS via Helm and via manifest per documentation steps.

CHORE Updated fluentbit deployments to new image

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/tail-sampling-values.yaml
otel-integration/k8s-helm/values.yaml

Upgrading Helm Chart Dependencies.

feat: upgrading chart dependencies

---

otel-ecs-fargate/README.md
otel-ecs-fargate/config.yaml
otel-ecs-fargate/parameter_store.cf

Move away from ADOT in favor of OTEL Collector Contrib for ECS Fargate integration. Documentation has been done.
Deployed into ECS Fargate testing environment via documented installation steps.
- [] This change does not affect any particular component (e.g. it's CI or docs change)

FEAT - Switch to Contrib from ADOT

---

otel-collector-windows-image/Dockerfile

Bump Windows image to latest collector version.

Bump Windows image to collector version 0.104.0

---

.github/workflows/otel-collector-windows-image.yml

We need to adjust the base image and pin to specific SHA in order to work around issue which prevents successful builds. More info on the issue and workaround is here https://github.com/microsoft/Windows-Containers/issues/493/.

Work around issue for Windows 2019 image

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-281
Updates collector version for Windows to `0.104.0` and brings the Windows values file up to date.
On a test EKS cluster.

[otel-integration] Update Windows image to `0.104.0`

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values.yaml

- changelog
- added scrapeInterval default
- added brief note regarding configuring scrape interval in target allocator
- bump chart version
Fixes #

es-313 Added configuration option for Scrape Interval in Target Allocator

---

.github/workflows/Sync-integration-definition.yaml

To improve the flow, of releasing a new version for `otel-integration/k8s-helm/Chart.yaml` in the UI, made an update to the sync action to push change directly to master in the integration-definition repo instead of creating a PR
Fixes #

Update sync-integration-definition action to push changes to master instead of creating a pr [CDS-1442]

---

.github/workflows/Sync-integration-definition.yaml

Right now the sync action will try to push changes directly to master, it is not possible because  the repo required all status checks to pass before committing changes, to fix this issue, changed the action to create PR wait for all of the `all status check` to pass and then it will merge it.
Fixes #

bug fix in sync-integration-definition [CDS-1442]

---

logs/fluent-bit/ecs-fargate/README.md
otel-ecs-fargate/CHANGELOG.md
otel-ecs-fargate/README.md
otel-ecs-fargate/config.yaml
otel-ecs-fargate/parameter_store.cf

ECS Fargate integration now processes logs via OTEL instead of extra fluentbit container.
This integration was deployed, taskdefinition launched, and logs and metrics observed in CX.
- [] I have updated the relevant Helm chart(s) version(s)

[BREAKING][MAJOR] Update ECS Fargate integration to submit logs using OTEL vs fluentbit

---

otel-ecs-fargate/CHANGELOG.md
otel-ecs-fargate/README.md

Updated ECS Fargate documentation with example of private key via Secrets Manager.
CDS-1609
Deployed to ECS Fargate.

Ecs fargate docs secrets manager private key

---

otel-eks-fargate/CHANGELOG.md
otel-eks-fargate/README.md
otel-eks-fargate/cx-eks-fargate-otel-self-monitoring.yaml
otel-eks-fargate/cx-eks-fargate-otel.yaml

Updated EKS Fargate OTLP receiver to accept HTTP payloads on 4318.
Simple config change, no testing completed.

Eks fargate http receiver

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values.yaml

This PR adds the error tracking spanmetrics preset. 
Fixes ES-385 by bringing the changes from https://github.com/coralogix/opentelemetry-helm-charts/pull/120.
Deployed to kind running locally.

[opentelemetry-integration] Add the errorTracking spanmetrics preset

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-386.
Makes the metrics telemetry service listen on `0.0.0.0` instead of using shell var expansion to resolve the pod IP by bringing in the changes from https://github.com/coralogix/opentelemetry-helm-charts/pull/121.
Local kind cluster.

[opentelemetry-integration] Fix metrics telemetry server address

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-386
Locally with kind.

[opentelemetry-integration] Change default value for metrics telemetry service address

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/central-agent-values.yaml
otel-integration/k8s-helm/central-tail-sampling-values.yaml
otel-integration/k8s-helm/ci/tail-sampling-values.yaml
otel-integration/k8s-helm/gke-autopilot-values.yaml
otel-integration/k8s-helm/tail-sampling-values.yaml
otel-integration/k8s-helm/values-cluster-ksm.yaml
otel-integration/k8s-helm/values-crd-override.yaml
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

This PR adds the ebpf tracing agent subchart
1. Package the new chart:
- Set domain and clusterName in the values.yaml file
- `helm lint ./otel-integration/k8s-helm`
- `helm dependency build ./otel-integration/k8s-helm`
- `helm package ./otel-integration/k8s-helm`
3. Create a new namespace on the cluster: `k create ns test-ebpf-agent-subchart`
4. Create a new coralogix-keys secret: `k create secret generic coralogix-keys -n test-ebpf-agent-subchart --from-literal=PRIVATE_KEY=bogus`
5. Install the chart while setting `enabled=true` for the subchart: `helm install cx-otel-shippers /Users/mattia.meleleo/cx/telemetry-shippers/otel-integration-0.0.114.tgz --namespace test-ebpf-agent-subchart --set coralogix-ebpf-agent.enabled=true`
6. Observe the created resources are running as expected

otel-integration: add ebpf agent subchart

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

updated otel endpoint in ebpf agent to send data otel agent instead of collector
deployed ebpf agent using helm and watched spans reach coralogix

bump ebpf-agent chart version

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values-ebpf-agent-existing-collector.yaml
otel-integration/k8s-helm/values.yaml

increased ebpf agent version to 0.1.7
added a way to deploy ebpf agent for an existing collector setup
created a new k8s cluster
setup a otel collector sending to coralogix not as part as the helm chart
and the ran
```
helm dependency build ./otel-integration/k8s-helm
helm package ./otel-integration/k8s-helm
helm install cx-otel ./otel-integration-0.0.125.tgz --namespace coralogix-ebpf  --create-namespace -f otel-integration/k8s-helm/values-ebpf-agent-existing-collector.yaml --set coralogix-ebpf-agent.ebpf_agent.otel.exporter.endpoint="http://otel-collector-sandbox.default.svc.cluster.local:4317"
```
then validate spans are reaching the collector / coralogix instance

deploy ebpf agent without collector

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-383.
- Make the `opentelemetry-receiver` Collector report agent type `receiver` to discern it from the gateway one.
- Add fleet management preset configuration to the Windows values files.
All the other collectors are already well configured in the main `values.yaml` file.
Run it in `kind`.

Fleet management updates

---

otel-eks-fargate/cx-eks-fargate-otel-self-monitoring.yaml
otel-eks-fargate/cx-eks-fargate-otel.yaml

Fixes ES-299.
Document how to enable the fleet management feature in EKS Fargate.
Tested in an EKS Fargate-only cluster.

[otel-eks-fargate] Document how to use the fleet management feature

---

otel-ecs-fargate/README.md
otel-ecs-fargate/parameter_store_cf.yaml

Fixes ES-299.
Document how to enable the fleet management feature in ECS Fargate.
Tested in an ECS Fargate cluster.

[otel-ecs-fargate] Document the fleet management feature in ECS Fargate

---

.gitignore
otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-401.
Bumps the Collector chart to bring in the extra attributes used for the pod association in the k8s attributes processor.
This should add things like CronJob attributes in Job metrics, among others.
Local kind cluster.

[otel-integration] Add more attributes to the pod association for the k8s attributes processor

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-411.
Narrow down the metrics service host back to the pod ip after the original issue was solved upstream in the OpenTelemetry Operator since version v0.116.0.
Local kind cluster.

[opentelemetry-integration] Narrow down metrics service host back to pod ip

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/e2e-test/expected_test.go
otel-integration/k8s-helm/values.yaml

Fixes ES-408.
EKS with Windows and Linux nodes.

[opentelemetry-integration] Bump OTEL Collector to version 0.117.0

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-304.
This adds the missing `source_identifier` configuration to recombines passed to the integration through `presets.logsCollection.multilineConfigs`.
Local kind cluster.

[opentelemetry-integration] Fix missing `source_identifier` in multiline configs

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-319.
Moves the memory limiter processor to the top of all the pipelines in which it is present. This is the recommended best practice according to the [processor's documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md#best-practices).
Tested locally in a `kind` cluster.

[opentelemetry-integration] Prioritize memory limiter processor in all pipelines

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/central-agent-values.yaml
otel-integration/k8s-helm/central-tail-sampling-values.yaml
otel-integration/k8s-helm/ci/tail-sampling-values.yaml
otel-integration/k8s-helm/gke-autopilot-values.yaml
otel-integration/k8s-helm/tail-sampling-values.yaml
otel-integration/k8s-helm/values-cluster-ksm.yaml
otel-integration/k8s-helm/values-crd-override.yaml
otel-integration/k8s-helm/values-ebpf-agent-existing-collector.yaml
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-490.
Add `opentelemetry-ebpf-profiler` subchart.

[ES-490] Add opentelemetry-ebpf-profiler subchart.

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/central-agent-values.yaml
otel-integration/k8s-helm/central-tail-sampling-values.yaml
otel-integration/k8s-helm/ci/tail-sampling-values.yaml
otel-integration/k8s-helm/gke-autopilot-values.yaml
otel-integration/k8s-helm/tail-sampling-values.yaml
otel-integration/k8s-helm/values-cluster-ksm.yaml
otel-integration/k8s-helm/values-crd-override.yaml
otel-integration/k8s-helm/values-ebpf-agent-existing-collector.yaml
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Reverting commit `36884f7418983d4092286ac2dfd19aa700c91ea8` because it seems it is producing some issues to customers even when disabled.
Some customers have some systems where they download all the images even when they are not using some subcharts. Since the `ebpf-profiler` image is not there yet, this is causing some issues.

Remove ebpf-profiler from subcharts

---

otel-integration/k8s-helm/e2e-test/fleet_manager_test.go

Fixes ES-550.
We delete the pods created by the Helm chart to trigger them to be recreated and restart the opamp connection. This ensures we get the minimum amount of messages to pass the test much more reliably.

[ci] Make the fleet-manager test less flaky

---

.gitignore
logs/CHANGELOG.md
logs/fluent-bit/image/Dockerfile
logs/fluent-bit/k8s-helm/http/Chart.yaml
logs/fluent-bit/k8s-helm/http/README.md
logs/fluent-bit/k8s-helm/http/values.yaml
logs/fluent-bit/k8s-manifest/README.md
logs/fluent-bit/k8s-manifest/fluentbit-cm.yaml
logs/fluent-bit/k8s-manifest/fluentbit-ds.yaml

Fixes CDS-2086.
> Fluent Bit traditionally offered a classic configuration mode, a custom configuration format that we are gradually phasing out. While classic mode has served well for many years, it has several limitations. Its basic design only supports grouping sections with key-value pairs and lacks the ability to handle sub-sections or complex data structures like lists.
> 
> YAML, now a mainstream configuration format, has become essential in a cloud ecosystem where everything is configured this way. To minimize friction and provide a more intuitive experience for creating data pipelines, we strongly encourage users to transition to YAML. The YAML format enables features, such as processors, that are not possible to configure in classic mode.
> 
> As of Fluent Bit v3.2, you can …

update/CDS-2086: rewrite fluent-bit k8s configuration to YAML

---

otel-eks-fargate/CHANGELOG.md
otel-eks-fargate/cx-eks-fargate-otel.yaml

The value of `k8s_node_name` label set in telemetry from this integration is incorrect. It is incorrectly set to the **node** where the `fargate-otel-collector pod` is running
Fixes # CDS-2130
Verified in lab and with customer that the correct value is set after removing the k8s.node.name upsert in the resource/metadata processor.

[otel-eks-fargate] Fix incorrect overwrite of k8s.node.name

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-629.
Brings the fixes from https://github.com/coralogix/opentelemetry-helm-charts/pull/218.
Local tests.

[otel-integration] Fix image template helper with Supervisor preset

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/central-agent-values.yaml
otel-integration/k8s-helm/tail-sampling-values.yaml
otel-integration/k8s-helm/values.yaml

Fixes CDS-2254 by deploying https://github.com/coralogix/opentelemetry-helm-charts/pull/234
This change will add new variable `presets.coralogixExporter.pipelines` as an `array` of `string` to allow enabling exporter on 2 pipelines at once.
So that in cases where we want to disable, let's say, coralogix exporter only in one pipeline, we could do this:
```
opentelemetry-agent:
presets:
coralogixExporter:
enabled: true
pipelines: ["metrics", "traces"]
```
instead of this:
```
opentelemetry-agent:
presets:
coralogixExporter:
enabled: true
pipeline: "none"
config:
service:
pipelines:
metrics:
exporters:
- coralogix
traces:
exporters:
- coralogix
```
We've added a new variable instead of changing the existing one (`presets.coralogixExporter.pipeline`) for backward compatibility. The existing …

add presets.coralogixExporter.pipelines to allow enabling exporter on 2 pipelines at once

---

otel-integration/k8s-helm/README.md

Adds Coralogix OpenTelemetry chart link to:

CDS-2270 - Add GitHub link for the CX OpenTelemetry Chart

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/ipv6-values.yaml
otel-integration/k8s-helm/values.yaml

Support ipv6 for ebpf-profiler
I checked the helm otel-integration release with both ipv6 and ipv4 clusters.

An 331 ipv6

---

.github/workflows/Sync-integration-definition.yaml

https://coralogix.atlassian.net/browse/NGSTN-1969
`otel-agent-k8s` is now versioned differently; it's no longer tightly coupled with chart version, but it keeps chart version in build metadata part of semver. That PR aligns automated logic to handle that new versioning scheme. 
I've tested the updated script logic on my local machine
~~- [ ] I have updated the relevant Helm chart(s) version(s)~~
~~- [ ] I have updated the relevant component changelog(s)~~
~~- [ ] This change does not affect any particular component (e.g. it's CI or docs change)~~

Update integration-definition workflow to handle new versioning scheme
