CHANGELOG.md

Update app versions upgrade in Changelog

Update apps versions upgrades in Changelog

---

.github/workflows/fluentd-ecs-image.yml

1. change folder name to lowercase
2. update workflow name
3. fix workflow version path

fluentd ecs fixes

---

opel-agent/exmaples/otel-demo-docker-compose/README.md

Update readme with source code link

Update otel example readme

---

fluentd/aws-ecs/image/dockerfile

fixed to copy since there was a typo

fixed the copy from firelens in dockerfile

---

.github/workflows/fluentd-ecs-image.yml

context for GitHub action is wrong

Fix Context

---

opel-agent/CHANGELOG.md
opel-agent/Chart.yaml
opel-agent/values.yaml

Enable hostNetwork by default

---

fluentd/aws-ecs/image/Dockerfile

As agreed, changed the docker image tag from "latest" to the specific version (v0.0.9)

Dockerfile fix

---

fluent-bit/dashboard/fluent-bit-dashboard.json

Had a few updates and fixes in the fluentbit dashboard, including fixing the `pods variable` to include pods from multiple fluentbits if we have some, add the `mean column` [avg] to a few panels, add `totals` to some panels

Update Fluentbit Grafana Dashboard

---

fluent-bit/http/templates/luascript-cm.yaml

- new validation when dynamic field is nil

fix: missing dot in dynamic metadata

---

.github/workflows/fluent-bit-coralogix-chart.yml
.github/workflows/fluent-bit-http-chart.yml
.github/workflows/fluentd-coralogix-chart.yml
.github/workflows/fluentd-http-chart.yml

fix for path-ignore used incorrectly for some of the github automations.

fix: fix github ignore path used incorrectly

---

.github/workflows/prometheus-operator.yml
metrics/prometheus/operator/Chart.lock
metrics/prometheus/operator/Chart.yaml
metrics/prometheus/operator/README.md
metrics/prometheus/operator/exporters/README.md
metrics/prometheus/operator/values.yaml

coralogix prometheus operator chart

feat: adding prometheus operator chart

---

README.md
logs/fluent-bit/coralogix/values.yaml
logs/fluent-bit/http/values.yaml
logs/fluentd/coralogix/values.yaml
logs/fluentd/http/values.yaml

- fix main readme docs
- fix all fluent integration to use the correct secret

fix: use 'coralogix-keys' secret.

---

README.md
metrics/prometheus/operator/Chart.lock

- updated main readme
- removed Chart.lock

fix: fixed automation.

---

otel-agent/dashboard/otel-agent-dashboard.json

Added variables for appname and subsystem and added them to all metrics that have these labels. (queue metrics for instance dont have these labels so no need)

Update otel agent dashboard json and add appname subsystem variables

---

otel-agent/CHANGELOG.md
otel-agent/Chart.yaml
otel-agent/values.yaml

Add support for thrift_binary , added to ports list

Add support for thrift_binary protocol in jaeger receiver

---

otel-agent/README.md

Adding a new section to the readme about the span processor - SimpleSpanProcessor vs BatchSpanProcessor and its impact on the collector performance

Add performance section regarding a span processor to the readme

---

README.md
otel-agent/README.md
otel-infrastructure-collector/README.md

Signed-off-by: Matej Gera <matej.gera@coralogix.com>
Small addition to the readme to make clear users need to first add our repo.

Otel-agent: Instruct user to add repo

---

metrics/prometheus-agent/README.md
metrics/prometheus-agent/values.yaml

I'm adding a recommendation section to the prometheus agent readme talking about persistent volumes.
Signed-off-by: Nicolas Takashi <nicolas.takashi@coralogix.com>

[FEAT] adding recommendation about volumes prom agent

---

.github/workflows/otel-agent.yml
otel-agent/ecs-ec2/README.md

- updated workflow paths
- readme
- added image description

Fix ghaction workflow 

---

.github/workflows/otel-agent.yml
otel-agent/ecs-ec2/README.md

- updated workflow paths
- readme
- added image description
- updated path

Fix gh actions

---

.github/CODEOWNERS
otel-agent/k8s-helm/README.md

The last workflow run failed, in order to trigger it again, we must merge to master

Update codeowners and trigger the pipeline to build the chart

---

metrics/prometheus-agent/README.md

Updating the endpoints to the new ones

Update Coralogix endpoints in Promethes agent readme

---

.github/workflows/otel-ecs-image.yml

- updated image version tag var
- added path for build trigger

fix ecs image

---

otel-infrastructure-collector/k8s-helm/CHANGELOG.md
otel-infrastructure-collector/k8s-helm/Chart.yaml

I'm upgrading Otel base chart to leverage new Otel version and k8sobject receivert.
Signed-off-by: Nicolas Takashi <nicolas.takashi@coralogix.com>

[FEAT] upgrading otel dependency chart

---

CHANGELOG.md
metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/values.yaml

We are upgrading the Prometheus-agent version to the latest.

[Feature] Upgrading prometheus agent

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/templates/service.yaml
metrics/prometheus-agent/templates/serviceMonitor.yaml
metrics/prometheus-agent/values.yaml

I'm adding the missing Prometheus Agent Service

[CHORE] adding prom agent svc

---

metrics/prometheus-agent/templates/service.yaml
metrics/prometheus-agent/templates/serviceMonitor.yaml

I'm fixing the selector labels on Prometheus Agent Service

[FIX] changing prometheus agent labels selector

---

otel-agent/ecs-ec2/config.yaml

Adds resource detection for Docker attributes to Otel Agent default config for metrics/traces

Update default otel configuration

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/values.yaml

I'm adding Prometheus Agent shard support.

[FEATURE] adding prometheus agent shard support

---

otel-infrastructure-collector/CHANGELOG.md
otel-infrastructure-collector/k8s-helm/Chart.yaml

[otel-infrastructure-collector] update collector to v0.75.0

[otel-infrastructure-collector] update collector to v0.75.0

---

otel-agent/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml

[otel-agent] update collector to 0.75.0

[otel-agent] update collector to 0.75.0

---

otel-agent/k8s-helm/values.yaml
otel-infrastructure-collector/k8s-helm/values.yaml

I'm configuring the otel agent to expose its own logs as JSON and as well as the infrastructure-collector deployment and also adding the missing config for metrics.

[CHORE] change otel telemetry config

---

otel-infrastructure-collector/k8s-helm/CHANGELOG.md
otel-infrastructure-collector/k8s-helm/Chart.yaml
otel-infrastructure-collector/k8s-helm/values.yaml

I'm upgrading the OTEL version to match the same config we have on this [PR](https://github.com/coralogix/telemetry-shippers/commit/9ebd56ae3bd6705879f863ca70dad892bbef5f9c).

[CHORE] upgrading otel version

---

CONTRIBUTING.md

#212 - Adding contributing guide

[CHORE] adding contributing guide

---

.github/workflows/chart-version-bump-check.yml
.github/workflows/checks.yml

Cleans up some leftovers after #222 (do not run on `master` and remove unused env var).
N/A

*: Clean up leftovers after recent workflow changes

---

.github/workflows/otel-collector-windows-image.yml

[SC-18267]
Follow up for #232 - fixes wrong workflow name and tag
N/A

Fix wrong tag and name for Windows image workflow

---

otel-agent/k8s-helm-windows/CHANGELOG.md
otel-agent/k8s-helm-windows/Chart.yaml
otel-agent/k8s-helm-windows/README.md
otel-agent/k8s-helm-windows/templates/_config.tpl
otel-agent/k8s-helm-windows/templates/_helpers.tpl
otel-agent/k8s-helm-windows/templates/deployment.yaml
otel-agent/k8s-helm-windows/templates/service.yaml
otel-agent/k8s-helm-windows/templates/statefulset.yaml
otel-agent/k8s-helm-windows/values.schema.json

[SC-18267]
* Add Service for DaemonSet, since windows does not support hostnetworking
* Fix includeCollectorLogs=true breaks configuration.
* Add support for Deployment and StatefulSet options.

[k8s-helm-windows] fix bugs and add Service

---

otel-agent/CHANGELOG.md
otel-agent/ecs-ec2/Dockerfile

Updated coralogixrepo/otel-coralogix-ecs-ec2 container build src version.
- [x ] I have updated the relevant Helm chart(s) version(s)
- [ x] I have updated the relevant component changelog(s)
- [ x] This change does not affect any particular component (e.g. it's CI or docs change)

Update ECS-EC2 docker container version

---

.github/workflows/checks.yml

Fixes incorrect parameter for logs changelog check (accidental leftover).
N/A

Fix changelog check for logs

---

.github/workflows/checks.yml
otel-agent/ecs-ec2/CHANGELOG.md
otel-agent/k8s-helm/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml
otel-agent/k8s-helm/values.yaml

Fixes #
ES-33 
Installed old version of otel-agent:
```
helm upgrade --install otel-coralogix-agent coralogix-charts-virtual/opentelemetry-coralogix -f test-values.yaml
```
then update to new one using:
```
helm dependency update
helm upgrade --install otel-coralogix-agent -f new-values.yaml .
```

[otel-agent] use coralogix opentelemetry-helm-charts fork

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/values.yaml

Upgrading Prometheus Agent to the latest Prometheus version
N/A

[CHORE] upgrading Prometheus Agent

---

.github/workflows/otel-ecs-image.yml

[CDS-305] fix failing ECS EC2 container build workflow

---

.github/workflows/otel-ecs-image.yml

[CDS-305] fix build tag

---

otel-agent/ecs-ec2/logging.yaml

[cds-485] fix errors in default logging.yaml for otel

---

otel-agent/k8s-helm/CHANGELOG.md
otel-agent/k8s-helm/Chart.yaml
otel-infrastructure-collector/CHANGELOG.md
otel-infrastructure-collector/k8s-helm/Chart.yaml
otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml

Upgrading the upstream chart to use the latest coralogix otel helm chart

[CHORE] upgrading upstream helm chart

---

otel-agent/k8s-helm-windows/README.md
otel-collector-windows-image/Dockerfile

Fixes missed version in URL for the collector binary.
N/A

[otel-collector-windows-image]  Fix version in URL

---

.github/workflows/chart-version-bump-check.yml
otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-134
Add feature to add priority class automatically based on chart input.
Locally

Add priority class feature

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml

Fixes https://coralogix.atlassian.net/browse/ES-154

[otel-integration] kubeletstats and k8s.deployment.name fixes

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values.yaml

Resolves https://coralogix.atlassian.net/browse/ES-155 and https://coralogix.atlassian.net/browse/ES-159
Adds the target allocator for agent feature, documents it and bumps collector to `v0.90.1`.
Locally on `kind` cluster.

Bump collector version and add target allocator feature

---

.github/workflows/Sync-integration-definition.yaml

@stsatlantis @povilasv 
Create a new action that will update [integration-definitions](https://github.com/coralogix/integration-definitions) repo When a new version is made to otel-integration/k8s-helm/Chart.yaml file.
The action will take the new version of the file, and create a new folder in integration-definitions under integrations/otel-agent-k8s with the new version name (integrations/otel-agent-k8s/v\<new version\>)  and copy the `commands.yaml`, `fields.yaml`, `integration_guide.yaml` files from the previous version to the new version folder.
The action will update the relevant manifest.yaml file with a new `revision` at the end of the file.
Fixes #

Create Sync-integration-definition.yaml [CDS-916]

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-178
Updates target allocator and collector sub-charts to fix issues mentioned in the changelog.
Locally with `kind`

Bump target allocator image and sub-charts

---

otel-collector-windows-image/Dockerfile

Bump image version  to match with our main chart.
N/A

[otel-collector-windows-image] Bump image to 0.91.0

---

otel-collector-windows-image/Dockerfile

Bump Windows image to bring it in sync with main chart.

Bump Dockerfile Windows image

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/_helpers.tpl
metrics/prometheus-agent/templates/prometheus.yaml

Adding the template to include image pull secrets
I run helm template with two different configs with image pull secrets and without image pull secrets.

[CHORE] adding prom agent image pull secrets

---

metrics/prometheus-agent/CHANGELOG.md
metrics/prometheus-agent/Chart.yaml
metrics/prometheus-agent/templates/prometheus.yaml
metrics/prometheus-agent/values.yaml

Adding ability to set pod metadata on Prometheus Agent
Helm template with new property values

[CHORE] adding prom metadata

---

otel-integration/k8s-helm/README.md

Adds information about warnings on latest Helm version.
N/A

Document Helm warnings

---

.mdox.validate.yaml
otel-integration/k8s-helm/README.md

The check action is failing on links for ps labels, so i have added a regex in .mdox.validate.yaml to ignore them.
Fixes #

fix the issue with check action regarding link to issues labels

---

otel-ecs-ec2/CHANGELOG.md
otel-ecs-ec2/README.md
otel-ecs-ec2/config.yaml

Configures batch sizing in line with our latest recommendation, see https://coralogix.atlassian.net/browse/ES-53
N/A

[OTEL ECS EC2] Configure batch processor sizing

---

otel-agent/k8s-helm/README.md
otel-ecs-ec2/README.md
otel-integration/k8s-helm/README.md

Update README.md formatting

---

otel-integration/CHANGELOG.md

Update CHANGELOG.md - add warning about span metrics processor

---

.github/CODEOWNERS

Remove Amit, who is no longer member of the organization.

Update CODEOWNERS (remove deactivated user)

---

otel-collector-windows-image/Dockerfile
otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/e2e-test/expected_test.go
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-188
Locally

Bump collector and add metrics expiration configuration

---

otel-integration/CHANGELOG.md
otel-integration/UPGRADING.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/e2e-test/expected_test.go
otel-integration/k8s-helm/e2e-test/main_test.go
otel-integration/k8s-helm/values-windows-tailsampling.yaml
otel-integration/k8s-helm/values-windows.yaml
otel-integration/k8s-helm/values.yaml

Fixes https://coralogix.atlassian.net/browse/ES-336
Locally

Bump collector `0.107.0`

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/central-agent-values.yaml
otel-integration/k8s-helm/values.yaml

fix: central collector k8s attributes and logs

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

This PR upgrades the base chart in order to introduce the fix applied: https://github.com/coralogix/opentelemetry-helm-charts/pull/110

[CHORE] upgrading otel base chart

---

otel-eks-fargate/cx-eks-fargate-otel.yaml

replace logging exporter to debug in eks fargate

---

otel-ecs-fargate/CHANGELOG.md
otel-ecs-fargate/parameter_store_cf.yaml

Updated Documentation and CF template to include support for Advanced Parameter Store.
Deployed to ECS Fargate cluster. Observed logs and metrics from my example application.

[DOCS] ECSFargate Advanced Parameter Store Support

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes CDS-1683 by bringing changes from https://github.com/coralogix/opentelemetry-helm-charts/pull/119.

[opentelemetry-integration] Add missing batch size to all recombine operators

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Brings in the changes in our OTEL collector from https://github.com/coralogix/opentelemetry-helm-charts/pull/123 and https://github.com/coralogix/opentelemetry-helm-charts/pull/124.

[opentelemetry-integration] Add new configs for the Target Allocator

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

- **changelog**
- **update chart versions**
Fixes #

[opentelemetry-integration] Fix Target Allocator configmap name conflict issue

---

otel-integration/k8s-helm/README.md

Fixes ES-299.
Added some documentation regarding the fleet management preset.

Add documentation regarding the fleet management preset

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

[otel-integration] add error_mode:ignore for semconv transformation

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-ebpf-agent-existing-collector.yaml
otel-integration/k8s-helm/values.yaml

Allow adding tolerations to ebpf-agent
Manually by installing the subchart

Allow adding tolerations to ebpf-agent

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

add MongoDB support to coralogix-ebpf-agent
/

feat: add mongodb support to coralogix-ebpf-agent

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/values-ebpf-profiler-existing-collector.yaml
otel-integration/k8s-helm/values-ebpf-profiler.yaml
otel-integration/k8s-helm/values.yaml

add sub chart #AN-206

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Update helm version to support scrapeAll metrics option

[otel-integration] feat add scrapeAll option to otel

---

.github/workflows/Sync-integration-definition.yaml

Change dummy ticket to be in all caps so the ticket validation will pass in integration-definitions.
Fixes #

fix issue with Sync action

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/README.md
otel-integration/k8s-helm/e2e-test/expected_test.go
otel-integration/k8s-helm/values.yaml

Fixes CDS-2133 by introducing the upstream collector chart update from https://github.com/coralogix/opentelemetry-helm-charts/pull/173

update upstream collector chart to 0.114.1

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

use otel-k8s-cache image instead of beyla

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

bump profiler chart version, allowing for passing custom images to init containers

bump profiler version AN-382

---

otel-integration/CHANGELOG.md
otel-integration/UPGRADING.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

bump obi AN-391

---

otel-integration/k8s-helm/README.md

This PR documents all the reduced costs presets that were added in with #628.

[otel-integration] Document reduced attributes

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-700 and ES-698.
Brings the changes from https://github.com/coralogix/opentelemetry-helm-charts/pull/266 and https://github.com/coralogix/opentelemetry-helm-charts/pull/267.

[otel-integration] Profile support & update for reduce resource attributes

---

otel-integration/UPGRADING.md

Update UPGRADING.md requested by COE

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values.yaml

Fixes ES-716.
In our boutique cluster and examples.

[otel-integration] Fix resource attributes of the Collector's logs

---

otel-ecs-fargate/CHANGELOG.md
otel-ecs-fargate/config.yaml

Fix Syntax Error.
Added Spanmetrics to configuration.
Locally and by a test customer

Cds 2359 - Spanmetrics ECS Fargate

---

otel-ecs-fargate/parameter_store_cf.yaml

CDS-2359 - update CFN for otel ecs fargate

---

otel-integration/CHANGELOG.md
otel-integration/k8s-helm/Chart.yaml
otel-integration/k8s-helm/values-eks-fargate.yaml
otel-integration/k8s-helm/values.yaml

ES-56: port support for EKS Fargate
